name: GitHub-Profile-Summary-Cards

on:
  schedule: # 24시간마다 실행
    - cron: "0 0 * * *"
  workflow_dispatch: # 수동 실행 버튼도 사용 가능

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          THEME: "default"
